// <auto-generated />
namespace Repository.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class acodetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acodetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201912101620026_acode-time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
