// <auto-generated />
namespace Repository.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class emptyforupdatedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emptyforupdatedb));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111418510_empty-for-update-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
