// <auto-generated />
namespace Repository.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class memberedit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(memberedit));
        
        string IMigrationMetadata.Id
        {
            get { return "202104140535512_memberedit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
